CREATE TABLE CUST_PROFILE (
  CUST_PROFILE_ID INT NOT NULL PRIMARY KEY,
  FIRSTNAME VARCHAR(50) NULL DEFAULT NULL,
  LASTNAME VARCHAR(50) NULL DEFAULT NULL,
  CITY VARCHAR(50) NULL DEFAULT NULL,
  PHONE INT NULL DEFAULT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE CARD (
    CARD_ID INT NOT NULL PRIMARY KEY,
    CARD_TYPE VARCHAR(255) CHECK (CARD_TYPE IN ('DEBIT_CARD', 'CREDIT_CARD')),
    CARD_NUMBER VARCHAR(50) NULL DEFAULT NULL,
    CVV_NUMBER INT NOT NULL DEFAULT NULL,
    TOTAL_LIMIT INT NULL DEFAULT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE ACCOUNT (
  ACCT_ID INT NOT NULL PRIMARY KEY,
  ACCT_NUM VARCHAR(50) NULL DEFAULT NULL,
  BALANCE INT NULL DEFAULT NULL,
  ACCT_STAT VARCHAR(50) NULL DEFAULT NULL,
  FK_CUST_PROFILE_ID INT,
  FK_CARD_ID INT,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP NOT NULL,
  foreign key (FK_CUST_PROFILE_ID) references CUST_PROFILE(CUST_PROFILE_ID),
  foreign key (FK_CARD_ID) references CARD(CARD_ID)
)