CREATE TABLE CUST_PROFILE (
  CUST_PROFILE_ID INT NOT NULL PRIMARY KEY,
  FIRSTNAME VARCHAR(50) NULL DEFAULT NULL,
  LASTNAME VARCHAR(50) NULL DEFAULT NULL,
  CITY VARCHAR(50) NULL DEFAULT NULL,
  PHONE INT NULL DEFAULT NULL
);

CREATE TABLE ACCOUNT (
  ACCT_ID INT NOT NULL PRIMARY KEY,
  ACCT_NUM VARCHAR(50) NULL DEFAULT NULL,
  BALANCE INT NULL DEFAULT NULL,
  ACCT_STAT VARCHAR(50) NULL DEFAULT NULL,
  CUST_PROFILE_ID INT,
  foreign key (CUST_PROFILE_ID) references CUST_PROFILE(CUST_PROFILE_ID)
)